const crypto=require('crypto');
const {waitUntil}=require('@vercel/functions');
module.exports.config={api:{bodyParser:false}};

if(!global._cb)global._cb=new Map();
const isBlocked=k=>Date.now()<(global._cb.get(k)||0);
const blockFor=(k,ms)=>{global._cb.set(k,Date.now()+ms);console.warn('[CB]',k,'blocked',Math.round(ms/1000),'s');};
if(!global._dedup)global._dedup=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clean=t=>String(t||'').replace(/[*_~`#]/g,'').trim();
const CITY_FIX={faizabad:'Faisalabad',faizaabad:'Faisalabad',faisalabaad:'Faisalabad',faisalbad:'Faisalabad',fisalabad:'Faisalabad',lahroe:'Lahore',lhaore:'Lahore',karaachi:'Karachi',karachy:'Karachi',rwalpindi:'Rawalpindi',gujranwla:'Gujranwala'};
const fixCities=t=>t?t.replace(/\b([A-Za-z]+)\b/g,w=>CITY_FIX[w.toLowerCase()]||w):t;

function alreadyProcessed(id){if(!id)return false;const now=Date.now();for(const[k,v]of global._dedup)if(v<=now)global._dedup.delete(k);if((global._dedup.get(id)||0)>now)return true;global._dedup.set(id,now+600000);return false;}
function getPKT(){try{const p={};for(const x of new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Karachi',weekday:'long',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()))p[x.type]=x.value;return`${p.weekday} ${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute} PKT`;}catch(e){console.warn('[TIME]',e.message);return'PKT unavailable';}}

let neonSql=null;
function getNeon(url){if(!url||!url.startsWith('postgres'))return null;if(!neonSql){try{neonSql=require('@neondatabase/serverless').neon(url);}catch(e){console.error('[DB INIT]',e.message);}}return neonSql;}
const cache=new Map();
async function dbGet(url,phone){if(cache.has(phone))return cache.get(phone);const sql=getNeon(url);if(!sql)return null;try{const r=await sql`SELECT history,customer_name FROM zara_conversations WHERE phone_number=${phone} LIMIT 1`;if(r.length){const d={history:r[0].history||[],customerName:r[0].customer_name||''};cache.set(phone,d);return d;}}catch(e){console.error('[DB GET]',e.message);}return null;}
async function dbSave(url,phone,name,history){cache.set(phone,{history,customerName:name});const sql=getNeon(url);if(!sql)return;try{await sql`INSERT INTO zara_conversations(phone_number,customer_name,history,last_seen,msg_count) VALUES(${phone},${name||''},${JSON.stringify(history.slice(-20))}::jsonb,NOW(),${history.length}) ON CONFLICT(phone_number) DO UPDATE SET customer_name=EXCLUDED.customer_name,history=EXCLUDED.history,last_seen=NOW(),msg_count=EXCLUDED.msg_count`;}catch(e){console.error('[DB SAVE]',e.message);}}
let schemaPromise=null;
async function ensureSchema(url){const sql=getNeon(url);if(!sql)return false;if(!schemaPromise)schemaPromise=(async()=>{await sql`CREATE TABLE IF NOT EXISTS zara_processed_messages(message_id TEXT PRIMARY KEY,phone_number TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'processing',locked_until TIMESTAMPTZ DEFAULT NOW(),processed_at TIMESTAMPTZ)`;await sql`ALTER TABLE zara_processed_messages ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'processing'`;await sql`ALTER TABLE zara_processed_messages ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ DEFAULT NOW()`;await sql`ALTER TABLE zara_processed_messages ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ`;await sql`CREATE TABLE IF NOT EXISTS zara_orders(order_id TEXT PRIMARY KEY,phone_number TEXT NOT NULL,message_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',error TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW())`;return true;})().catch(e=>{console.error('[DB SCHEMA]',e.message);schemaPromise=null;return false;});return schemaPromise;}
async function claimMessage(url,id,phone){if(!id)return true;if(!(await ensureSchema(url)))return null;const sql=getNeon(url);try{const r=await sql`INSERT INTO zara_processed_messages(message_id,phone_number,status,locked_until) VALUES(${id},${phone},'processing',NOW()+INTERVAL '10 minutes') ON CONFLICT(message_id) DO UPDATE SET status='processing',locked_until=NOW()+INTERVAL '10 minutes' WHERE zara_processed_messages.status='failed' OR(zara_processed_messages.status='processing' AND zara_processed_messages.locked_until<NOW()) RETURNING message_id`;return r.length>0;}catch(e){console.error('[DB DEDUP]',e.message);return null;}}
async function markMessage(url,id,status){const sql=getNeon(url);if(!sql||!id)return;try{await sql`UPDATE zara_processed_messages SET status=${status},processed_at=CASE WHEN ${status}='processed' THEN NOW() ELSE NULL END,locked_until=NOW() WHERE message_id=${id}`;}catch(e){console.error('[DB DEDUP UPDATE]',e.message);}}
async function claimOrder(url,id,phone,msg){if(!url)return'unavailable';if(!(await ensureSchema(url)))return'error';const sql=getNeon(url);try{const r=await sql`INSERT INTO zara_orders(order_id,phone_number,message_id,status) VALUES(${id},${phone},${msg},'pending') ON CONFLICT(order_id) DO UPDATE SET updated_at=NOW() RETURNING status`;return r[0]?.status||'pending';}catch(e){console.error('[DB ORDER CLAIM]',e.message);return'error';}}
async function markOrder(url,id,status,error=''){const sql=getNeon(url);if(!sql)return;try{await sql`UPDATE zara_orders SET status=${status},error=${String(error).slice(0,500)},updated_at=NOW() WHERE order_id=${id}`;}catch(e){console.error('[DB ORDER UPDATE]',e.message);}}

const ROMAN_URDU=new Set('hai hain ho houn hun tha thi the aap ap apki aapki kia kya kyun kyon kaise kaisa karna karo karein krna krdo chahiye chahye mujhe mujhy ham hum mera meri mere apna apni yeh ye woh wo kahan kab abhi phir acha achha bohat bahut bhi se ko mein main pe par ke ki ka aur ya lekin magar sirf sab kuch koi nahi nahin ji jana do dein dena lena len bhej bhejo bata batayein batana mil milega rate qeemat keemat suit kapra kapray delivery shehar ghar order chahi raha rahi rahe sakti sakta pasand theek thik shukriya meharbani'.split(' '));
function detectLang(t){const s=String(t||'').trim();if(!s)return'roman_urdu';const u=(s.match(/[\u0600-\u06FF]/g)||[]).length,l=(s.match(/[A-Za-z]/g)||[]).length;if(u>=2&&u>=l*.35)return'urdu';const w=(s.toLowerCase().match(/[a-z]+/g)||[]),rh=w.filter(x=>ROMAN_URDU.has(x)).length,eh=w.filter(x=>['the','this','that','what','which','where','when','how','can','could','would','please','want','need','price','cost','available','availability','return','exchange','hello','hi','thanks','thank','your','you','we','i','me','my','is','are','do','does','did','will','send','show'].includes(x)).length;if(rh>=1&&rh>=eh)return'roman_urdu';if(eh>=1)return'english';return'roman_urdu';}
function langLock(text,history){let lang=detectLang(text);if(String(text||'').trim().length<=12&&Array.isArray(history)){for(let i=history.length-1;i>=0;i--){if(history[i]?.role!=='user')continue;const p=history[i]?.parts?.[0]?.text||'';if(p&&p.trim()!==String(text||'').trim()){lang=detectLang(p);break;}}}return lang==='urdu'?'Reply ONLY in Urdu script (اردو).':lang==='english'?'Reply ONLY in English.':'Reply ONLY in Roman Urdu using Latin letters.';}

function parseOrderTag(text){const m=String(text||'').match(/\[ORDER:([^\]]+)\]/i);if(!m)return null;const o={};for(const p of m[1].split('|')){const[k,...v]=p.split('=');if(k&&v.length)o[k.trim().toLowerCase()]=v.join('=').trim();}return Object.keys(o).length?o:null;}
function confirmed(text){const s=String(text||'').toLowerCase().replace(/[.!?,،؛:]/g,' ');return/(^|\s)(yes|yup|yeah|confirm|confirmed|ok|okay|haan|han|bilkul|theek|thik|done|proceed)(\s|$)/i.test(s)||/order\s+(confirm|kar|kardo|kardain|kar dein|bhej|bhej dein)/i.test(s)||/(kar\s+dein|kar\s+do|bhej\s+dein|bhej\s+do)/i.test(s)||/(^|\s)(ہاں|تصدیق|ٹھیک|ٹھیک ہے|کر دیں|آرڈر کر دیں)(\s|$)/u.test(s);}
function validateOrder(o){if(!o||typeof o!=='object')return'invalid_order';for(const k of['name','product','qty','price','payment','address','city'])if(!String(o[k]??'').trim())return`missing_${k}`;const q=Number(o.qty),p=Number(String(o.price).replace(/,/g,''));if(!Number.isInteger(q)||q<1||q>1000)return'invalid_qty';if(!Number.isFinite(p)||p<=0||p>10000000)return'invalid_price';if(!['cod','jazzcash','easypaisa'].includes(String(o.payment).toLowerCase().trim()))return'invalid_payment';if(String(o.address).trim().length<8)return'invalid_address';if(String(o.city).trim().length<2)return'invalid_city';return null;}
let gtok={token:null,exp:0};
async function googleToken(email,key){if(gtok.token&&Date.now()<gtok.exp-300000)return gtok.token;try{const now=Math.floor(Date.now()/1000),b=s=>Buffer.from(s).toString('base64url'),h=b(JSON.stringify({alg:'RS256',typ:'JWT'})),p=b(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',exp:now+3600,iat:now})),sign=crypto.createSign('RSA-SHA256');sign.update(`${h}.${p}`);const sig=sign.sign(key.replace(/\\n/g,'\n'),'base64url'),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${h}.${p}.${sig}`}),d=await r.json();if(d.access_token){gtok={token:d.access_token,exp:Date.now()+(d.expires_in||3600)*1000};return gtok.token;}console.error('[GTOKEN]',d.error||d.error_description||'token failure');}catch(e){console.error('[GTOKEN]',e.message);}return null;}
async function saveOrder(env,o,phone,msgId,userText){if(!env.sid||!env.email||!env.key)return console.error('[SHEET] Google Sheets configuration missing');if(!confirmed(userText))return console.warn('[ORDER GUARD] Customer confirmation missing');const bad=validateOrder(o);if(bad)return console.error('[ORDER GUARD]',bad);const token=await googleToken(env.email,env.key);if(!token)return false;const id=crypto.createHash('sha256').update(`${phone}:${msgId}`).digest('hex').slice(0,24);const claim=await claimOrder(env.db,id,phone,msgId);if(claim==='saved')return true;if(claim==='error')return false;try{const check=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${env.sid}/values/Sheet1!K:K`,{headers:{Authorization:`Bearer ${token}`}});if(!check.ok){await markOrder(env.db,id,'failed',`check ${check.status}`);return false;}const vals=(await check.json()).values||[];if(vals.some(r=>String(r?.[0]||'')===id)){await markOrder(env.db,id,'saved');return true;}const row=[[new Date().toLocaleString('en-PK',{timeZone:'Asia/Karachi'}),o.name,phone,o.product,o.qty,o.price,String(o.payment).toUpperCase(),o.address,o.city,'Pending',id]];const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${env.sid}/values/Sheet1!A:K:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({values:row})});if(!res.ok){const e=await res.text();await markOrder(env.db,id,'failed',e);console.error('[SHEET FAIL]',res.status,e.slice(0,150));return false;}await markOrder(env.db,id,'saved');console.log('[SHEET] Order saved ✓',id);return true;}catch(e){console.error('[SHEET]',e.message);return false;}}

async function rawBody(req){if(Buffer.isBuffer(req.rawBody))return req.rawBody;if(typeof req.rawBody==='string')return Buffer.from(req.rawBody);if(Buffer.isBuffer(req.body))return req.body;if(typeof req.body==='string')return Buffer.from(req.body);if(req.readable){const a=[];for await(const c of req)a.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(a);}return Buffer.alloc(0);}
function validSignature(raw,sig,secret){if(!secret||!sig)return false;const [scheme,hex]=String(sig).split('=',2);if(scheme!=='sha256'||!/^[a-f0-9]{64}$/i.test(hex||''))return false;const digest=crypto.createHmac('sha256',secret).update(raw).digest('hex');try{const a=Buffer.from(digest,'hex'),b=Buffer.from(hex,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}catch(e){return false;}}

async function aiChat(url,key,model,messages){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{return await fetch(`${url}/chat/completions`,{method:'POST',signal:c.signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages,temperature:.7,max_tokens:800})});}finally{clearTimeout(t);}}
const historyCache=new Map();

module.exports=async(req,res)=>{
  const env={token:(process.env.WHATSAPP_TOKEN||'').trim(),phoneId:(process.env.PHONE_NUMBER_ID||'').trim(),verify:(process.env.VERIFY_TOKEN||'').trim(),secret:(process.env.WHATSAPP_APP_SECRET||'').trim(),gemini:(process.env.GEMINI_API_KEY||'').trim(),groq:(process.env.GROQ_API_KEY||'').trim(),eleven:(process.env.ELEVENLABS_API_KEY||'').trim(),voice:(process.env.ELEVENLABS_VOICE_ID||'EXAVITQu4vr4xnSDxMaL').trim(),jazz:(process.env.JAZZCASH_NUMBER||'').trim(),easy:(process.env.EASYPAISA_NUMBER||'').trim(),cerebras:(process.env.CEREBRAS_API_KEY||'').trim(),router:(process.env.OPENROUTER_API_KEY||'').trim(),db:(process.env.DATABASE_URL||'').trim(),sid:(process.env.GOOGLE_SHEETS_ID||'').trim(),email:(process.env.GOOGLE_SA_EMAIL||'').trim(),key:(process.env.GOOGLE_SA_KEY||'').trim()};
  if(req.method==='GET'){const u=new URL(req.url,`https://${req.headers.host||'localhost'}`);if(u.searchParams.get('hub.mode')){if(u.searchParams.get('hub.mode')==='subscribe'&&u.searchParams.get('hub.verify_token')===env.verify)return res.status(200).send(u.searchParams.get('hub.challenge'));return res.status(403).send('Verification Token Mismatch');}return res.status(200).send('Webhook Active');}
  if(req.method!=='POST')return res.status(200).send('OK');
  const raw=await rawBody(req);if(!env.secret)return res.status(500).send('Webhook security configuration missing');if(!validSignature(raw,req.headers['x-hub-signature-256'],env.secret))return res.status(401).send('Invalid signature');
  let body=req.body;if(Buffer.isBuffer(body))body=body.toString('utf8');if(!body)body=raw.toString('utf8');if(typeof body==='string'){try{body=JSON.parse(body);}catch(e){return res.status(400).send('Invalid JSON');}}
  const value=body?.entry?.[0]?.changes?.[0]?.value,messages=Array.isArray(value?.messages)?value.messages:[],contacts=Array.isArray(value?.contacts)?value.contacts:[];if(!messages.length)return res.status(200).send('EVENT_RECEIVED');if(!env.token||!env.phoneId){console.error('[CONFIG] WhatsApp credentials missing');return res.status(200).send('EVENT_RECEIVED');}
  const work=(async()=>{const m=messages[0],mid=m?.id||'';try{if(!m?.from)return;const phone=m.from;const dbClaim=await claimMessage(env.db,mid,phone);if(dbClaim===false)return;if(dbClaim===null)console.warn('[DEDUP] DB unavailable; local fallback');if(alreadyProcessed(mid))return;const contact=contacts.find(c=>c?.wa_id===phone)||contacts[0]||{},name=(contact?.profile?.name||'').trim();const audio=m.type==='audio'||m.type==='voice';let hist=(await dbGet(env.db,phone))?.history||historyCache.get(phone)||[];let text='';
    if(m.type==='text')text=fixCities(m.text?.body||'');else if(audio&&env.groq){const id=m.audio?.id||m.voice?.id;if(id){const mr=await fetch(`https://graph.facebook.com/v20.0/${id}`,{headers:{Authorization:`Bearer ${env.token}`}});if(mr.ok){const md=await mr.json();if(md?.url){const ar=await fetch(md.url,{headers:{Authorization:`Bearer ${env.token}`}});if(ar.ok){const fd=new FormData();fd.append('file',new Blob([await ar.arrayBuffer()],{type:'audio/ogg'}),'voice.ogg');fd.append('model','whisper-large-v3-turbo');fd.append('language','ur');fd.append('prompt','Fatima Arts, Zara, Faisalabad, Lahore, Karachi, lawn, khaddar, marina, velvet, price, delivery, Pakistani customer');const wr=await fetch('https://api.groq.com/openai/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${env.groq}`},body:fd});if(wr.ok)text=fixCities((await wr.json()).text||'');}}}}}if(!text)text='[Customer ne voice message bheja — unse poochein kya chahiye]';}else if(m.type==='image')text='[Customer ne image bheji — poochein kya chahiye]';else if(m.type==='sticker')text='[Customer ne sticker bheja — friendly acknowledgment do]';else text='[Customer ne kuch bheja — friendly acknowledgment do]';if(!text.trim())text='Assalam o Alaikum';
    const lock=langLock(text,hist),prompt=`Aap Zara hain — Fatima Arts ki warm sales agent. Kabhi AI, automation ya software ka zikr na karein. Current time PKT: ${getPKT()}\nLANGUAGE LOCK: ${lock}\nRoman Urdu preferred for voice, but obey LANGUAGE LOCK exactly.\nCities: Faisalabad, Lahore, Karachi, Islamabad, Rawalpindi, Multan, Gujranwala, Peshawar, Quetta.\nRetail 1 suit=3600 rupees, delivery separate. Wholesale 10+=2999/suit. Payments: JazzCash ${env.jazz||'boss se confirm karein'}, EasyPaisa ${env.easy||'boss se confirm karein'}, COD.\nOrder only after explicit customer confirmation and output tag: [ORDER:name=CustomerName|product=Product|qty=1|price=3600|payment=COD|address=Full Address|city=Faisalabad]. Never promise unapproved discounts.`;
    const gem=[...hist,{role:'user',parts:[{text:(name?`Customer name: ${name}\n`:'')+text}]}],msgs=[{role:'system',content:prompt},...hist.map(x=>({role:x.role==='model'?'assistant':'user',content:x.parts?.[0]?.text||''})),{role:'user',content:(name?`Customer name: ${name}\n`:'')+text}];let reply='';
    if(env.gemini){for(const model of['gemini-3.7-flash','gemini-3.6-flash']){if(reply||isBlocked('g:'+model))continue;for(let a=0;a<2&&!reply;a++){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${env.gemini}`,{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({system_instruction:{parts:[{text:prompt}]},contents:gem,generationConfig:{temperature:.7,maxOutputTokens:800}})});if(r.ok){const d=await r.json();reply=clean(d.candidates?.[0]?.content?.parts?.[0]?.text);break;}if(r.status===429){blockFor('g:'+model,300000);break;}if(r.status===503){await sleep(1500);}}catch(e){if(e.name!=='AbortError')console.warn('[GEMINI]',e.message);}finally{clearTimeout(t);}}}}
    const fallbacks=[[env.cerebras,'https://api.cerebras.ai/v1','llama-3.3-70b','cerebras'],[env.groq,'https://api.groq.com/openai/v1','openai/gpt-oss-120b','groq'],[env.router,'https://openrouter.ai/api/v1','mistralai/mistral-7b-instruct:free','router']];for(const[f,k,model,label]of fallbacks){if(reply||!f)continue;try{const r=await aiChat(k,f,model,msgs);if(r.ok){reply=clean((await r.json()).choices?.[0]?.message?.content);break;}if(r.status===429)blockFor(label,300000);}catch(e){console.warn('['+label+']',e.message);}}
    if(!reply)reply='Thori dair mein wapas aati hoon, system busy hai.';const tag=parseOrderTag(reply);if(tag){reply=reply.replace(/\[ORDER:[^\]]+\]/gi,'').trim();await saveOrder(env,tag,phone,mid,text);}reply=fixCities(reply)||'Shukriya sabr ka 🙏';hist.push({role:'user',parts:[{text}]},{role:'model',parts:[{text:reply}]});if(hist.length>20)hist=hist.slice(-20);historyCache.set(phone,hist);await dbSave(env.db,phone,name,hist);
    let sentVoice=false;if(audio&&env.eleven){try{const tr=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${env.voice}`,{method:'POST',headers:{'xi-api-key':env.eleven,'Content-Type':'application/json','Accept':'audio/mpeg'},body:JSON.stringify({text:reply,model_id:'eleven_multilingual_v2',voice_settings:{stability:.5,similarity_boost:.75}})});if(tr.ok){const fd=new FormData();fd.append('messaging_product','whatsapp');fd.append('file',new Blob([await tr.arrayBuffer()],{type:'audio/mpeg'}),'voice.mp3');fd.append('type','audio/mpeg');const up=await fetch(`https://graph.facebook.com/v20.0/${env.phoneId}/media`,{method:'POST',headers:{Authorization:`Bearer ${env.token}`},body:fd});const ud=await up.json();if(ud.id){const sr=await fetch(`https://graph.facebook.com/v20.0/${env.phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${env.token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:phone,type:'audio',audio:{id:ud.id}})});sentVoice=sr.ok;}}}catch(e){console.error('[TTS]',e.message);}}
    if(!sentVoice){const sr=await fetch(`https://graph.facebook.com/v20.0/${env.phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${env.token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:phone,type:'text',text:{body:reply}})});if(!sr.ok)throw new Error('WhatsApp text send failed: '+sr.status);}
    await markMessage(env.db,mid,'processed');}catch(e){console.error('[CRITICAL ERROR]',e.message);await markMessage(env.db,mid,'failed');}})();waitUntil(work);return res.status(200).send('EVENT_RECEIVED');
};
