const $=id=>document.getElementById(id);let orders=[],live={leads:[],conversations:[],products:[]};
function money(n){return new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(Number(n)||0)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function navigate(section){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.section===section));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='sec-'+section));const titles={dashboard:'Dashboard',leads:'Lead Management',chat:'WhatsApp Inbox',products:'Product Catalog',orders:'Orders & Invoices',analytics:'Sales Analytics',pitch:'Sales Pitches',settings:'Settings'};$('pageTitle').textContent=titles[section]||section;$('sidebar').classList.remove('open');if(section==='orders')renderOrders();if(section==='analytics')renderAnalytics()}
function renderOrders(){const body=$('ordersTable'),recent=$('recentOrders');if(!orders.length){body.innerHTML='<tr><td colspan="12" class="empty">No orders found in the production sheet.</td></tr>';recent.innerHTML='<tr><td colspan="5" class="empty">No saved orders yet.</td></tr>';return}body.innerHTML=orders.map(o=>`<tr><td>${esc(o.orderId)}</td><td>${esc(o.date)}</td><td>${esc(o.name)}</td><td>${esc(o.phone)}</td><td>${esc(o.product)}</td><td>${esc(o.qty)}</td><td>${esc(o.size)}</td><td>${esc(o.color)}</td><td>${money(o.total)}</td><td>${esc(o.address)}</td><td>${esc(o.payment)}</td><td><span class="badge green">${esc(o.status||'Pending')}</span></td></tr>`).join('');recent.innerHTML=orders.slice(0,5).map(o=>`<tr><td>${esc(o.orderId)}</td><td>${esc(o.name)}</td><td>${esc(o.product)}</td><td>${money(o.total)}</td><td><span class="badge green">${esc(o.status||'Pending')}</span></td></tr>`).join('')}
function renderAnalytics(){const total=orders.reduce((s,o)=>s+Number(o.total||0),0),pending=orders.filter(o=>String(o.status||'').toLowerCase()==='pending').length,aov=orders.length?total/orders.length:0;$('aOrders').textContent=orders.length||'0';$('aRevenue').textContent=money(total);$('aAov').textContent=money(aov);$('aPending').textContent=pending;const map={};orders.forEach(o=>map[o.product]=(map[o.product]||0)+Number(o.total||0));const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]);$('productPerformance').innerHTML=rows.length?rows.map((x,i)=>`<div class="rank-item"><span>${i+1}. ${esc(x[0])}</span><b>${money(x[1])}</b></div>`).join(''):'<div class="empty">No product sales yet.</div>'}
function renderChart(){const chart=$('orderChart');if(!orders.length){chart.innerHTML='<div class="chart-empty">No saved order history yet.</div>';return}const byDay={};orders.forEach(o=>{const d=String(o.date||'').slice(0,10)||'Unknown';byDay[d]=(byDay[d]||0)+Number(o.total||0)});const rows=Object.entries(byDay).sort((a,b)=>a[0].localeCompare(b[0])).slice(-10);const max=Math.max(...rows.map(x=>x[1]),1);chart.innerHTML=`<div style="width:100%;height:100%;display:flex;align-items:flex-end;gap:10px;padding:20px 8px 8px">${rows.map(x=>`<div style="flex:1;height:100%;display:flex;flex-direction:column;justify-content:flex-end;gap:6px"><div title="${esc(x[0])}: ${money(x[1])}" style="height:${Math.max(5,x[1]/max*88)}%;background:linear-gradient(180deg,#d8ad38,#7c5b08);border-radius:6px 6px 2px 2px;min-height:6px"></div><small style="color:#68778b;text-align:center;font-size:8px">${esc(x[0].slice(5))}</small></div>`).join('')}</div>`}
function renderLiveModules(){
  const leadPage=document.querySelector('#sec-leads .empty-state');
  if(leadPage){
    if(!live.leads.length) leadPage.innerHTML='<div>◉</div><h3>No live customer conversations yet</h3><p>When Zara records customer memory, this area will populate automatically. No fake leads are shown.</p>';
    else leadPage.innerHTML=`<div style="width:100%;text-align:left"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:16px"><div class="panel" style="padding:14px"><small>Customers</small><h3 style="margin:4px 0">${live.leads.length}</h3></div><div class="panel" style="padding:14px"><small>Conversations</small><h3 style="margin:4px 0">${live.conversations.length}</h3></div><div class="panel" style="padding:14px"><small>Known preferences</small><h3 style="margin:4px 0">${live.leads.filter(x=>x.fabric||x.color).length}</h3></div></div><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>City</th><th>Preference</th><th>Messages</th><th>Last activity</th></tr></thead><tbody>${live.leads.slice(0,50).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.city)}</td><td>${esc([x.fabric,x.color].filter(Boolean).join(' · '))}</td><td>${x.messages}</td><td>${x.lastAt?esc(new Date(x.lastAt).toLocaleString('en-PK')):'—'}</td></tr>`).join('')}</tbody></table></div></div>`;
  }
  const chatList=document.querySelector('#sec-chat .chat-list');
  if(chatList){
    const search=document.getElementById('chatSearch');
    const rows=live.conversations;
    chatList.innerHTML=`<div class="search">⌕ <input id="chatSearch" placeholder="Search conversations"></div><div id="conversationRows">${rows.length?rows.map(x=>`<div class="panel" style="margin:8px;padding:12px;cursor:pointer"><div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(x.name)}</b><small>${x.lastAt?esc(new Date(x.lastAt).toLocaleDateString('en-PK')):''}</small></div><div style="font-size:12px;color:#8d9aae;margin-top:5px">${esc(x.preview)}</div></div>`).join(''):'<div class="empty-chat">No stored customer conversations yet.</div>'}</div>`;
    document.getElementById('chatSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#conversationRows .panel').forEach(el=>el.style.display=el.textContent.toLowerCase().includes(q)?'block':'none')});
  }
  const productPage=document.querySelector('#sec-products .empty-state');
  if(productPage){
    if(!live.products.length) productPage.innerHTML='<div>▦</div><h3>No live catalogue records available</h3><p>The dashboard will never invent products. Your existing Zara catalogue pipeline remains untouched.</p>';
    else productPage.innerHTML=`<div style="width:100%;text-align:left"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px">${live.products.map(p=>{const img=p.images?.[0]?.url||'';return `<article class="panel" style="padding:0;overflow:hidden"><div style="height:170px;background:#111b2b;display:flex;align-items:center;justify-content:center">${img?`<img src="${esc(img)}" alt="${esc(p.name)}" style="width:100%;height:100%;object-fit:cover" loading="lazy">`:'<span style="color:#718096">No image</span>'}</div><div style="padding:14px"><b>${esc(p.name)}</b><div style="font-size:12px;color:#8d9aae;margin:5px 0">${esc([p.fabric,p.collection,p.color].filter(Boolean).join(' · '))}</div><strong>${money(p.price)}</strong><div style="font-size:12px;margin-top:6px">${p.stock===null?'Stock not verified':`${p.stock} in stock`}</div></div></article>`}).join('')}</div></div>`;
  }
}
async function load(){try{const r=await fetch('/api/dashboard-data',{headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Dashboard API unavailable');orders=Array.isArray(d.orders)?d.orders:[];$('connectionText').textContent='Live · Google Sheets';$('sheetStatus').textContent='Connected';$('syncState').textContent='Synced';$('statOrders').textContent=orders.length;$('statOrdersTrend').textContent='Live production data';const total=orders.reduce((s,o)=>s+Number(o.total||0),0),aov=orders.length?total/orders.length:0;$('statRevenue').textContent=money(total);$('statAov').textContent=money(aov);$('funnelOrders').textContent=orders.length;$('funnelRevenue').textContent=money(total);renderOrders();renderChart();renderAnalytics();
  try{const lr=await fetch('/api/dashboard-live',{headers:{Accept:'application/json'}});const ld=await lr.json();if(ld.ok&&ld.available){live={leads:Array.isArray(ld.leads)?ld.leads:[],conversations:Array.isArray(ld.conversations)?ld.conversations:[],products:Array.isArray(ld.products)?ld.products:[]};$('leadBadge').textContent=live.leads.length||'0';$('unreadBadge').textContent=live.conversations.length||'0';renderLiveModules();}}catch(_){/* orders remain available even if CRM/catalogue is unavailable */}
}catch(e){$('connectionText').textContent='Dashboard API unavailable';$('sheetStatus').textContent='Not available';$('syncState').textContent='Waiting';toast('Live dashboard data is not available yet. Zara is unaffected.')}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>navigate(a.dataset.section)));document.querySelectorAll('[data-section-jump]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.sectionJump)));$('menuToggle').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('refreshBtn').addEventListener('click',()=>{load();toast('Refreshing live data…')});$('ordersRefresh').addEventListener('click',()=>{load();toast('Orders refreshed')});load()});