'use strict';
const crypto=require('node:crypto');
function secret(){return String(process.env.DASHBOARD_PASSWORD||process.env.VERIFY_TOKEN||'').trim()}
function sign(value){return crypto.createHmac('sha256',secret()).update(value).digest('hex')}
function cookieValue(){return `zara_session.${sign('zara-dashboard')}`}
function authorized(req){const s=secret();if(!s)return false;const raw=String(req.headers?.cookie||'');const m=raw.match(/(?:^|;\s*)zara_session=([^;]+)/);if(!m)return false;const a=Buffer.from(m[1]),b=Buffer.from(cookieValue());return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function setCookie(res){res.setHeader('Set-Cookie',`zara_session=${cookieValue()}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`)}
function loginPage(){return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Zara AI — Secure Dashboard</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07101d;color:#edf3fa;font:15px Inter,system-ui,sans-serif}.box{width:min(380px,calc(100% - 36px));padding:28px;border:1px solid #20334b;border-radius:20px;background:#0d1726;box-sizing:border-box}h1{margin:0 0 8px;font-size:25px}p{color:#8d9bae;line-height:1.5}input,button{width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid #20334b;background:#111b29;color:#fff;margin-top:10px}button{background:#4f8cff;border:0;font-weight:800;cursor:pointer}</style></head><body><form class="box" method="post" action="/api/dashboard-auth"><h1>Zara AI</h1><p>Secure Sales Command Center</p><input name="password" type="password" autocomplete="current-password" placeholder="Dashboard password" required><button>Open dashboard</button></form></body></html>'}
module.exports={secret,authorized,setCookie,loginPage};
