'use strict';
const { neon } = require('@neondatabase/serverless');
function sqlFor(){const u=String(process.env.DATABASE_URL||'').trim();return u.startsWith('postgres')?neon(u):null}
async function ensure(sql){if(!sql)return;await sql`CREATE TABLE IF NOT EXISTS zara_human_control (phone_number TEXT PRIMARY KEY, human_active BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
async function isHuman(phone){const sql=sqlFor();if(!sql)return false;try{await ensure(sql);const r=await sql`SELECT human_active FROM zara_human_control WHERE phone_number=${phone} LIMIT 1`;return Boolean(r[0]?.human_active)}catch(e){console.error('[HUMAN CONTROL]',e.message);return false}}
async function setHuman(phone,active){const sql=sqlFor();if(!sql)throw new Error('DATABASE_URL is not configured');await ensure(sql);await sql`INSERT INTO zara_human_control(phone_number,human_active,updated_at) VALUES(${phone},${Boolean(active)},NOW()) ON CONFLICT(phone_number) DO UPDATE SET human_active=EXCLUDED.human_active,updated_at=NOW()`;return Boolean(active)}
async function getConversation(phone){const sql=sqlFor();if(!sql)throw new Error('DATABASE_URL is not configured');const r=await sql`SELECT phone_number,customer_name,history,last_seen,msg_count FROM zara_conversations WHERE phone_number=${phone} LIMIT 1`;return r[0]||null}
async function saveConversation(phone,name,history){const sql=sqlFor();if(!sql)throw new Error('DATABASE_URL is not configured');await sql`INSERT INTO zara_conversations(phone_number,customer_name,history,last_seen,msg_count) VALUES(${phone},${name||''},${JSON.stringify(history.slice(-20))}::jsonb,NOW(),${history.length}) ON CONFLICT(phone_number) DO UPDATE SET customer_name=EXCLUDED.customer_name,history=EXCLUDED.history,last_seen=NOW(),msg_count=EXCLUDED.msg_count`}
module.exports={isHuman,setHuman,getConversation,saveConversation};
