'use strict';
const crypto=require('node:crypto');
const {neon}=require('@neondatabase/serverless');
function sqlFor(){const u=String(process.env.DATABASE_URL||'').trim();return u.startsWith('postgres')?neon(u):null}
async function ensure(sql){if(!sql)return;await sql`CREATE TABLE IF NOT EXISTS zara_orders (id TEXT PRIMARY KEY,phone_number TEXT NOT NULL,order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),customer_name TEXT NOT NULL,product_name TEXT NOT NULL,quantity NUMERIC NOT NULL,unit_price NUMERIC NOT NULL,total_amount NUMERIC NOT NULL,payment_method TEXT NOT NULL,address TEXT NOT NULL,city TEXT NOT NULL,size TEXT NOT NULL DEFAULT '',color TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Pending',fingerprint TEXT NOT NULL UNIQUE,source TEXT NOT NULL DEFAULT 'whatsapp',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
function normalizeOrder(order,phone){if(!order||!phone)return null;const out={name:String(order.name||'').trim().slice(0,160),product:String(order.product||'').trim().slice(0,240),qty:String(order.qty||'').replace(/[^\d.]/g,'').trim(),price:String(order.price||'').replace(/[^\d.]/g,'').trim(),payment:String(order.payment||'').trim(),address:String(order.address||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,500),city:String(order.city||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,80)};if(!out.name||!out.product||!out.qty||!out.price||!out.payment||!out.address||!out.city)return null;if(!/^\d+(?:\.\d+)?$/.test(out.qty)||Number(out.qty)<1||Number(out.qty)>100)return null;if(!/^\d+(?:\.\d+)?$/.test(out.price)||Number(out.price)<=0||Number(out.price)>1000000)return null;if(!/^(?:cod|cash on delivery|jazzcash|easypaisa)$/i.test(out.payment))return null;if(out.address.length<8||out.city.length<2)return null;return out}
function fingerprint(order,phone){return crypto.createHash('sha256').update([phone,order.name,order.product,order.qty,order.price,order.payment.toLowerCase(),order.address.toLowerCase(),order.city.toLowerCase()].join('|')).digest('hex')}
async function saveConfirmedOrder(order,phone,source='whatsapp'){const sql=sqlFor();if(!sql)return {ok:false,reason:'database_not_configured'};const normalized=normalizeOrder(order,phone);if(!normalized)return {ok:false,reason:'validation'};const fp=fingerprint(normalized,phone),id=`FA-${fp.slice(0,10).toUpperCase()}`,qty=Number(normalized.qty),unit=Number(normalized.price),total=qty*unit;try{await ensure(sql);const rows=await sql`INSERT INTO zara_orders(id,phone_number,customer_name,product_name,quantity,unit_price,total_amount,payment_method,address,city,fingerprint,source) VALUES(${id},${phone},${normalized.name},${normalized.product},${qty},${unit},${total},${normalized.payment},${normalized.address},${normalized.city},${fp},${source}) ON CONFLICT(fingerprint) DO NOTHING RETURNING id`;if(!rows.length)return {ok:true,duplicate:true,id};return {ok:true,duplicate:false,id}}catch(e){console.error('[ORDER STORE]',e.message);return {ok:false,reason:'database_write_failed'}}}
async function listOrders(limit=100){const sql=sqlFor();if(!sql)return {available:false,orders:[]};try{await ensure(sql);const rows=await sql`SELECT id,order_date,customer_name,phone_number,product_name,quantity,unit_price,total_amount,address,city,payment_method,size,color,status FROM zara_orders ORDER BY order_date DESC LIMIT ${Math.min(Math.max(Number(limit)||100,1),200)}`;return {available:true,orders:rows.map(o=>({orderId:o.id,date:o.order_date,name:o.customer_name,phone:o.phone_number,product:o.product_name,qty:Number(o.quantity),size:o.size||'',color:o.color||'',total:Number(o.total_amount)||0,address:[o.address,o.city].filter(Boolean).join(', '),payment:o.payment_method,status:o.status||'Pending'}))}}catch(e){console.error('[ORDER LIST]',e.message);return {available:false,orders:[]}}}
module.exports={saveConfirmedOrder,listOrders,normalizeOrder};
